### POST 점메추 식당 추가 - 리스트
POST http://localhost:5001/slash-command/lunch/new
content-type: application/json

{
  "lists": [
    {
      "name": "타코디스코",
      "link": "https://map.naver.com/p/entry/place/1192436184?c=15.00,0,0,0,dh&placePath=/menu",
      "type": "ETC"
    }
  ]
}

### POST 점메추 카테고리에 따른 추천 받기
POST http://localhost:5001/slash-command/lunch/interact
content-type: application/json

{
  "user": {
    "id": "13838",
    "email": "testEmail"
  },
  "actionName": "GET_RECOMMENDATION",
  "actionValue": "KOREAN",
  "tenant": {
    "id": "id",
    "domain": "domain"
  }
}

### POST 점메추 처음 시작하기
POST http://localhost:5001/slash-command/lunch
content-type: application/json

{
  "userId": "13838"
}

### POST 점메추 추천 시작하기
POST http://localhost:5001/slash-command/lunch/interact
content-type: application/json

{
  "user": {
    "id": "13838",
    "email": "testEmail"
  },
  "actionName": "START",
  "actionValue": "{\"responseType\":\"inChannel\",\"itemNo\":\"\",\"itemType\":\"\"}",
  "tenant": {
    "id": "id",
    "domain": "domain"
  }
}
